function [Lat, Lng, Altitude, LR_Altitude, Heading, Timestamp] = importLog(fileToRead1)
%IMPORTFILE(FILETOREAD1)
%  Imports data from the specified file
%  FILETOREAD1:  file to read

%  Auto-generated by MATLAB on 30-Nov-2015 13:35:54

% Import the file
newData1 = load(fileToRead1,'-mat');

% Create new variables in the base workspace from those fields.
% CTUN(:,7)=Alt, CTUN(:,10)=SAlt, CTUN_label, GPS(:,8)=Lat, GPS(:,9)=Lng, GPS(:,4)=GMS, GPS(:,5)=GWk, GPS_label

vars = {'CTUN', 'CTUN_label', 'GPS', 'GPS_label', 'ATT', 'ATT_label'}';
for i = 1:length(vars)
    assignin('base', vars{i}, newData1.(vars{i}));
end

Heading = newData1.ATT(:,8);

timezone = -8*3600000;

epoch = datenum('1980-01-06', 'yyyy-mm-dd'); 
elapsed = newData1.GPS(:,5).*(7*24*60*60*1000)+newData1.GPS(:,4)+timezone;

Timestamp = datenum(epoch + ((epoch +elapsed) ./ 8.64e7));

Altitude = newData1.CTUN(1:end-1,7);
LR_Altitude = newData1.CTUN(1:end-1,10);


x = (1:size(Timestamp,1))';
xi = (1:size(Timestamp,1)/size(newData1.CTUN(:,2),1):size(Timestamp,1))';
y_1 = Timestamp;
y_2 = newData1.GPS(:,8);
y_3 = newData1.GPS(:,9);
yi_1 = interp1q(x,y_1,xi);
yi_2 = interp1q(x,y_2,xi);
yi_3 = interp1q(x,y_3,xi);

Lng = yi_3;
Lat = yi_2;
Timestamp = yi_1;

datestr(Timestamp(1))
dlmwrite('meta_mission.csv',[Altitude Heading(1:end-1) Lat Lng],'delimiter',',','precision',15);

end